name: Test repository
on: 
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Yarn test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
