name: CI
on: 
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Yarn Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

  publish-npm:
    needs: test
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/') 
    steps:
      - uses: actions/checkout@v1
      - name: Yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Yarn publish
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}